### ISSUE TITLE
Should package definitions differ between YANG library and instance data docs?

### ISSUE THREAD

**Issue by rgwilton** [rgwilton/YANG-Packages-Draft#12]
Is it OK for the YANG definition used for package instance data vs YANG library to differ?  The reason for the difference is to allow "Module Sets" to be reused, potentially minimizing duplicate data in YANG library.

**Comment by BalazsLengyel** [comment]
No. I strongly disagree.  The online and offline formats should be the same with one single model.

Two formats are more complex. Leads to misunderstanding.

Some people will use yanglib to document server capabilities anyway. That will now include packages: and pronto we have two different formats for instance data about packages.

**Comment by rgwilton** [comment]
The formats have been unified after recent discussions.  The YANG package definition on the server is the same as the instance-data-document except that can contain multiple packages and carries a couple of extra fields (location and checksum).
